accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView
)

from .views import RegisterView
app_name = 'accounts'


urlpatterns = [
    path('login', LoginView.as_view(template_name='accounts/forms/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page= 'accounts:login'), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
]

dashboard/urls.py
from django.urls import path
from .views import (
    IndexView, NewCarouselImage, NewTomb, NewTombType
)

app_name  = 'dashboard'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('new/carousel/image', NewCarouselImage.as_view(), name='new_carousel_image'),
    path('new/tomb/type', NewTombType.as_view(), name='new_tomb_type'),
    path('new/tomb/<int:pk>', NewTomb.as_view(), name='new_tomb'),
]

groovestreet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import IndexView
app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

accounts/models.py
import django
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.pk})

dashboard/models.py
from django.db import models

# Create your models here.

home/models.py
from email.policy import default
from tabnanny import verbose
from django.db import models
from django.urls import reverse
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField
from django.contrib.gis.db.models import PointField
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager

User = get_user_model()


class CarouselImage(models.Model):
    image = models.ImageField(upload_to='ome/carousel/images/%Y/%m/%d', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Carousel Image'
        verbose_name_plural = 'Carousel Images'
    
    def __str__(self):
        return 'Carousel Image: {}'.format(str(self.created))

class TombType(models.Model):
    summary = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta: 
        verbose_name = 'Tomb Type'
        verbose_name_plural = 'Tomb Types'

    def __str__(self):
        return self.summary

    def get_absolute_url(self):
        return reverse('home:tomb_type_detail', kwargs={'pk': self.pk})

class Tomb(models.Model):
    tomb_type = models.ForeignKey(TombType, related_name='tombs', null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default='')
    description = RichTextField()
    location = PointField()
    tags = TaggableManager()
    curator = models.ForeignKey(User, related_name='tombs', on_delete=models.CASCADE, null=True) 
    created = models.DateTimeField(auto_now_add=True)


    class Meta: 
        verbose_name = 'Tomb'
        verbose_name_plural = 'Tombs'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:tomb_detail', kwargs={'pk': self.pk})

accounts/forms.py
from django import forms
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.gis.forms.fields import PointField
from mapwidgets.widgets import GooglePointFieldWidget


class NewUserForm(UserCreationForm):    
    location = PointField(widget=GooglePointFieldWidget())
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1']

home/forms.py
from django import forms
from django import forms
from .models import CarouselImage, TombType, Tomb
from ckeditor.fields import RichTextFormField


class CarouselImageForm(forms.ModelForm):

    class Meta:
        model = CarouselImage
        fields = ['image']



class TombTypeForm(forms.ModelForm):

    class Meta:
        model = TombType
        fields = ['summary']



class TombForm(forms.ModelForm):
    description = RichTextFormField()

    class Meta:
        model = Tomb
        exclude = ['curator', 'created']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView, DetailView, FormView, TemplateView
)
from django.views.generic.edit import (
    UpdateView, DeleteView
)
from .forms import NewUserForm


class RegisterView(FormView):
    template_name = 'accounts/forms/signup_form.html'
    form_class = NewUserForm
    success_url = '/accounts/profile'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


@login_required(login_url='/accountslogin')
def profile(request):
    if request.user.is_superuser:
        return redirect('dashboard:index')
    else:
        return redirect('home:index')

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    ListView, TemplateView, FormView, DetailView
)
from django.urls import reverse_lazy
from django.views.generic.edit import (
    FormMixin, UpdateView, DeleteView, CreateView
)

from home.models import (
    CarouselImage, TombType, Tomb
)
from home.forms import CarouselImageForm, TombForm, TombTypeForm
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(TemplateView):
    template_name = 'dashboard/index.html'

class NewCarouselImage(FormView):
    template_name = 'dashboard/forms/carousel_image_form.html'
    form_class = CarouselImageForm
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        image = form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)



class NewTombType( LoginRequiredMixin, FormView):
    login_url = '/accounts/login'
    template_name = 'dashboard/forms/tomb_type_form.html'
    form_class = TombTypeForm
    success_url = reverse_lazy('dashboard:index')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class NewTomb(LoginRequiredMixin, FormView):
    login_url = '/accounts/login'
    template_name = 'dashboard/forms/tom_form.html'
    form_class = TombForm

    def form_valid(self, form):
        tomb_type = TombType.objects.get(pk=self.kwargs['pk'])
        tomb = form.save(commit=False)
        tomb.tomb_type = tomb_type
        tomb.curator = self.request.user
        tomb.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    TemplateView, ListView, DetailView
)
from .models import CarouselImage



class IndexView(TemplateView):
    template_name = 'home/index.html'

    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        carousel_images = CarouselImage.objects.order_by('-created')
        context['carousel_images'] = carousel_images
        return context
    

accounts/templates/accounts/forms/login.html
{% extends 'home/header.html' %}
{% load static %}


{% block title %}
Sign In To Continue
    
{% endblock title %}
    

{% block content %}
<div id="login">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Continue</button>
    </form>
</div>
    
{% endblock content %}
    

accounts/templates/accounts/forms/signup_form.html
{% extends 'home/header.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %}
    Sign Up 
{% endblock title %}
    

{% block content %}
<head>

    {% block jquery %}
    <script src="{% static 'home/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'home/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'home/jquery-ui/jquery.timepicker.min.js' %}"></script>
    {% endblock jquery %}
</head>
<div id="block">
    <div id="sign-up">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            <div class="container">
                {{form|crispy}}
                <button type="submit" class="btn btn-secondary">Continue</button>
            </div>
        </form>
    </div>
</div>
    
{% endblock content %}
    

dashboard/templates/dashboard/forms/carousel_image_form.html
{% extends 'home/header.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
New Carousel Image
    
{% endblock title %}
    

{% block content %}
<div id="form-container" class="pt-5">
    <form action="" class="form-control" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">
            Continue
        </button>
    </form>
</div>
    
{% endblock content %}
    

dashboard/templates/dashboard/forms/tomb_type_form.html
{% extends 'home/header.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}

New Tomb Type
    
{% endblock title %}
    


{% block content %}
<div class="container">
    <h2>New Tomb Type</h2>
    <form action="" class="form-control" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-light">
            Continue
        </button>
    </form>
</div>
{% endblock content %}
    

dashboard/templates/dashboard/index.html
{% extends 'home/header.html' %}
{% load static %}



{% block title %}
    Dashboard
{% endblock title %}
    

{% block dashboard %}
<head>
    <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
</head>
<div id="dashboard-menu">
<nav class="nav">
    
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Blog Content
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#">New Topic</a></li>
          <li><a class="dropdown-item" href="#">All Topics</a></li>
        </ul>
      </div>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Home Page Content
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'dashboard:new_carousel_image' %}">Add Image To Carousel</a></li>
         
        </ul>
      </div>
</nav>
</div>    
{% endblock dashboard %}
    
{% block content %}

<div id="dashboard">
    <h1>Dashboard</h1>
</div>
    
{% endblock content %}
    

home/templates/home/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
        
    {% endblock title %}
        </title>
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'home/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'home/css/header.css' %}">
        <link rel="stylesheet" href="{% static 'home/owl/dist/assets/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static  'home/jquery-ui/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static  'home/jquery-ui/jquery-ui.structure.min.css'  %}">
        <link rel="stylesheet" href="{% static 'home/jquery-ui/jquery-ui.theme.min.css'  %}">
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>
<body>
    <div id="header" >
        <div id="brand">
            <h2 class="navbar-brand">Groove Street Memorial</h2>
        </div>
        <div id="nav">
            <div id="search">
                <form action="" method="GET">
                    <input type="search" >
                </form>
            </div>
            <div id="links">
                <a class="btn btn-light" href="">Home</a>
                <a class="btn btn-light" href="">Blog</a>
            </div>
        </div>
    </div>
    
    {% block dashboard %}
        
    {% endblock dashboard %}
        
    <div id="block">
        
        {% block content %}
            
        {% endblock content %}
            
    </div>


    {% block bootstrap %}
       <script src="{% static 'home/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% endblock bootstrap %}
    
    {% block jquery %}
    <script src="{% static 'home/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'home/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'home/jquery-ui/jquery.timepicker.min.js' %}"></script>
    {% endblock jquery %}

                
    {% block jscript %}
        
    {% endblock jscript %}

    
    {% block javascript %}
       
    {% endblock javascript %}
        
        
    
</body>
</html>

home/templates/home/index.html
{% extends 'home/header.html' %}
{% load static %}


{% block title %}
    Groove Street Memorial
{% endblock title %}



{% block content %}
<head>
  <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
</head>
    <div id="home">
        <h1 class="display-1 text-center">Groove Street Memorial</h1>
        <div id="carousel-container">

        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              
              {% for item in carousel_images %}
                
                {% if forloop.first %}
                <div class="carousel-item active">
                  <div class="image-container">
                    <img class="img-fluid" src="{{item.image.url}}"  alt="...">
                  </div>
                 
                </div>
                {% else %}
                <div class="carousel-item">
                  <div class="image-container">
                    <img class="img-fluid" src="{{item.image.url}}"  alt="...">
                  </div>
                </div>    
                {% endif %}
                  
              {% endfor %}
                
              
            </div>
          </div>
        </div>
    </div>
{% endblock content %}
    
    

home/templates/home/tagged_tombs.html
{% extends 'home/header.html' %}
{% load static %}


{% block title %}
{{tomb}}
    
{% endblock title %}
    


{% block content %}
<head>
    
</head>
<div id="tombs">
    
</div>
{% endblock content %}
    

home/templates/home/tomb_detail.html
{% extends 'home/header.html' %}
{% load static %}


{% block title %}
{{tomb}}
    
{% endblock title %}
    


{% block content %}
<head>

</head>

<div id="tomb">
    
</div>
{% endblock content %}
    